backend:
  name: github
  repo: brocktaylor7/marthataylorviolin
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: images
public_folder: /images

collections:
  - name: "content"
    label: "Site Content"
    files:
      - label: "Announcements"
        name: "announcements"
        file: "content/announcements.yaml"
        fields:
          - label: "Announcements"
            name: "body"
            widget: "markdown"
      - label: "Studio Policy"
        name: "policy"
        file: "content/policy.yaml"
        fields:
          - label: "Studio Policy"
            name: "body"
            widget: "markdown"
